run:
  concurrency: 4          # Moderate concurrency, you can adjust based on your system.
  timeout: 3m             # Linting will timeout after 3 minutes.
  tests: false            # Do not lint test files by default.
  issues-exit-code: 1     # Exit with code 1 if any issue is found.

linters:
  disable-all: true        # Disable all linters by default.
  enable:
    - gofmt                # Enforces gofmt formatting.
    - goimports            # Ensures imports are sorted.
    - govet                # Runs Go's vet tool for finding potential errors.
    - errcheck             # Ensures errors are checked.
    - staticcheck          # A collection of static analysis checks (highly recommended).
    - gosimple             # Simplifies Go code.
    - unused               # Checks for unused variables, constants, etc.
    - revive               # Code style and consistency linter.
    #   - gosec                # Finds potential security issues.

linters-settings:
  gofmt:
    simplify: true         # Simplify code using 'gofmt -s'.

  staticcheck:
    checks: ["all"]        # Enable all staticcheck checks (good for best practices).

  revive:
    ignore-generated-header: true # Ignore generated files with specific headers.
    severity: warning              # Set the severity of all rules to 'warning'.
    rules:
      - name: context-as-argument  # Enforce passing context.Context as the first argument.
      - name: errorf               # Enforce the use of `fmt.Errorf` for error formatting.
      - name: indent-error-flow    # Enforce proper error flow indentation.

issues:
  max-issues-per-linter: 0  # No limit on the number of issues reported per linter.
  max-same-issues: 0        # No limit on the number of the same issues reported.
  exclude-use-default: false # Do not use default exclusions (no need for most personal projects).

output:
  print-issued-lines: true  # Print the actual code line where the issue is found.
  print-linter-name: true   # Show the name of the linter for each issue.
  sort-results: true        # Sort results by filename and line number.

  exclude-dirs:
    - .github
    - .hooks
    - .vscode
    - snippets

  exclude-files:
    - README.md

